console.log(null>0);
console.log(null == 0);
console.log(null>=0);
console.log("-----------");
console.log(undefined > 0 );
console.log(undefined == 0);
console.log(undefined >= 0);
console.log("----------");
const id = Symbol('123');
const newid = Symbol('123');
console.log(typeof id);
